spring:
  application:
    name: chaeking
  profiles:
    active: local

  thymeleaf:
    check-template-location: true
    cache: false
  resources:
    static-locations:
      - classpath:/static/
    cache:
      period: 0

server:
  port: 8081
  tomcat:
    basedir: .
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    accesslog:
      enabled: true
      directory: logs
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %{X-Forwarded-For}i(%h) %l %u \"%r\" %s %b"
